### ISSUE TITLE
Discussion page wiki "Conventions collectives et accords"

### ISSUE THREAD

**Issue by laem** [betagouv/syso#113]

**Comment by georges-bayard** [comment]
La vision portée par le triptyque "mettre à disposition - explorer - calculer est parfaitement claire. En complément quelques idées.
En premier lieu : d'où partons nous ? Il existe aujourd'hui des outils qui permettent d'accéder à l'information, par exemple legifrance pour l'accès aux règles sous format brut, ou les fiches de service public (ajoutent d'une couche didactique davantage orientées utilisateurs). Ces approches ont néanmoins certaines limites. D'une part elles partent des textes et de situations abstraites et non de la situation vécue par les personnes : je décris ma situation, mon besoin, et je vais te dire les règles qui te sont applicables. Cette fonction est réservée à l'accompagnateur humain : syndicat, avocat, inspecteur du travail, ...
D'autre  part elles n'intègrent pas le droit conventionnel qui pourtant est appelé à prendre de plus en plus d'importance avec la nouvelle loi travail. Quelque soit l'endroit ou on se situe on va avoir de plus en plus de mal à répondre à une personne "voici les règles qui s'appliquent à toi ... sous réserve des conventions collectives dont je ne sais pas quelles sont celles qui s'appliquent à toi ni à fortiori t'expliquer le contenu."
Il ne s'agit donc pas aujourd'hui d'ignorer la richesse de l'existant mais bien de le compléter, d'apporter des couches de service complémentaires portant, en ce qui concerne les conventions collectives, sur le triptyque "mettre à disposition - explorer - calculer". Le service offert devra être suffisamment ouvert pour être consommé non seulement par l'utilisateur final mais également par des services existants qu'il permettra d'enrichir. Il s'agit de constituer des briques réutilisables.
