### ISSUE TITLE
Pouvoir saisir des opérations simples

### ISSUE THREAD

**Issue by laem** [betagouv/syso#134]
Étant donnée qu'on ne gère pas les périodes autres que le mois, on pourrait imaginer qu'un cadre, qui raisonne à l'année, saisisse `40000/12` comme salaire. On a toutes les briques pour le faire. 
Il faudrait surtout se demander comment faire comprendre cette fonctionnalité pour le moins inhabituelle.

**Comment by Morendil** [comment]
On pourrait s'inspirer de Calca: http://calca.io/

**Comment by johangirod** [comment]
Je pense qu'il serait plus intéressant de pouvoir changer la base temporel du calcul, tout simplement. Cette feature serait accessible à plus de monde que celle de la "calculette integrée" dans le champs input

**Comment by laem** [comment]
Oui c'est clairement plus intéressant... Mais plus difficile 😁
Il manque du contexte : on avait imaginé ça pour qu'un assimilé salarié président de SASU saisisse par ex. 16*500€ de tjm

**Comment by johangirod** [comment]
Yep, effectivement, ça a plus de sens. Mais c'est une feature difficilement découvrable, qui peut poser quelques problème (comment s'assurer que l'expression est valide, pouvoir ajouter des parenthèses, ...)

**Comment by johangirod** [comment]
Je suis pour la supression de cet demande de fonctionalité pour les raisons suivantes : 
- Difficilement découvrable
- Principal cas d'utilisation couvert par la conversion mois / année déjà en place
- Complexifie la validation de du champs de saisi (on passe du format nombre au format expression)
- Gain faible par rapport au travail demandé (l'utilisateur peut utiliser la calculette integrée à son OS)

**Comment by mquandalle** [comment]
D'accord avec @johangirod, c'est une fonctionnalité trop difficilement découvrable et avec un gain trop faible. Il est probable qu'un utilisateur qui veut calculer 16 × 500€ de TJM utilisera la calculatrice de son téléphone ou PC plutôt que d'écrire littéralement le calcul dans un champ de saisie de nombre.

Par ailleurs si le but est de couvrir des raisonnements en €/jour ou €/heure, autant l'avoir directement dans l'interface à côté de “mois” et “année”.
