### ISSUE TITLE
Cumul JEI - Réductions de cotisations

### ISSUE THREAD

**Issue by laem** [betagouv/syso#135]
Le cumul n'est pas possible : il faut choisir entre les réductions fillon et allocations familiales, et JEI (qui est aussi une réduction de cotisation et pas une aide différée). 
Ce serait bien que le simulateur fasse ce choix et sélectionne la plus avantageuse. Il faut améliorer le mécanisme `maximum` tel que décrit dans son test. 
Le comportement actuel est de privilégier la JEI si le statut JEI pour l'embauche est choisi. 
Il faut donc définir une nouvelle variables "réductions de cotisation" qui regroupe les 3.

**Comment by laem** [comment]
Il y a un fichier dans la base de règle qui parle de ce sujet.

**Comment by Morendil** [comment]
J'ai glané quelques infos, le choix de Fillon vs JEI est "irrévocable" d'après les URSSAF, par contre on peut cumuler JEI et taux réduit d'allocations familiales. Cf https://www.legisocial.fr/actualites-sociales/2068-comment-declarer-les-cotisations-dallocations-familiales-si-lentreprise-beneficie-du-regime-jei.html

**Comment by georges-bayard** [comment]
Taux réduit d'allocations familiales ? C'est un lapsus non ?

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

21 janv. 2018 11:27:59, Laurent Bossavit <notifications@github.com> a écrit :


J'ai glané quelques infos, le choix de Fillon vs JEI est "irrévocable" d'après les URSSAF, par contre on peut cumuler JEI et taux réduit d'allocations familiales. Cf https://www.legisocial.fr/actualites-sociales/2068-comment-declarer-les-cotisations-dallocations-familiales-si-lentreprise-beneficie-du-regime-jei.html

**Comment by Morendil** [comment]
@georges-bayard Non c'est comme ça que le présente le document en question mais aussi l'URSSAF: https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-taux-de-cotisations/la-cotisation-dallocations-famil.html

Qu'est-ce qui te surprend ?

**Comment by Morendil** [comment]
Pour mémoire voici la règle qu'on applique: https://embauche.beta.gouv.fr/regle/r%C3%A9duction-allocations-familiales - il faudrait supprimer la condition "≠ statut JEI" si j'ai bien analysé la page de legisocial.fr.
