### ISSUE TITLE
remarques georges

### ISSUE THREAD

**Issue by georges-bayard** [betagouv/syso#141]
- affichage des aides employeurs différées
- lisibilité des résultats : le passage du brut au net  et au salaire total n'est pas clair
- bug : sur la première page on peut sélectionner salaire brut, salaire net, salaire total et aides différées

**Comment by laem** [comment]
- tu veux dire qu'il n'y a pas de vue (ex. en tableau) affichée en dessous des résultats pour les aides différées ? est-ce que le clic ne suffit pas pour les curieux ?
- tu veux dire dans le tableau de résultat ? comment on peut l'améliorer ?
- le bug est corrigé.
