### ISSUE TITLE
Bug: Net, 5000, Brut, Net, 5000 => Net en haut ET en bas

### ISSUE THREAD

**Issue by Morendil** [betagouv/syso#144]
Est-ce lié au même bug que #142 ? (Le [Rookie Club](https://github.com/rookie-club/) mène l'enquête !)

**Comment by Morendil** [comment]
On décide de tester le symétrique:
- Brut, 5000, Net, Brut, 5000 => Sakada s'attend à voir la même somme (brut) en haut et en bas

**Comment by Morendil** [comment]
A notre grande surprise, dans ce cas on a un crash: "undefined is not an array". (Perso je m'attendais à ce que ça marche.)

**Comment by Morendil** [comment]
On décide de réduire le cas de test:
- Brut, Net, 5000

**Comment by Morendil** [comment]
On constate la même erreur dans le cas réduit

**Comment by Morendil** [comment]
On décide de tenter la réduction du cas symétrique:
- Net, Brut, 3900
On s'attend à voir la même erreur ("undefined is not an array")

**Comment by Morendil** [comment]
Effectivement on a la même erreur dans la console.

**Comment by Morendil** [comment]
- Yannick se demande si on a des aller-retour avec le serveur.
- Sakada se demande si "Changer d'objectif" fait la même chose que le bouton "Back".

Comme l'appli est une single page app, on décide de tester l'idée de Sakada sur Brut, Net 5000. Paul s'attend à ce qu'on observe l'erreur, car la navigation devrait avoir le même effet.

**Comment by Morendil** [comment]
On voit bien la même erreur.

On décide de tester Net (Back ou Changer), Net, 5000. Laurent s'attend à ce que ça marche dans ce cas car l'opération est idempotente. Puis Brut, back, Brut, 5000. Même raisonnement.

Effectivement pas de bug dans ce cas.

**Comment by Morendil** [comment]
Elodie suggère un test par instrumentation:
- on enregistrerait une trace dans le cas Net, 5000:
 - cocher "Net", puis Valider => tracer targetNames (on doit voir ["salaire net"])
 - saisir 5000 => tracer foldedSteps (on doit voir ["salaire de base"])
- on enregistrerait une trace dans le cas Brut, Net, 5000:
 - cocher "Brut", puis Valider => tracer targetNames (on doit voir ["salaire de base"])
 - cliquer "Changer d'objectif"
 - cocher "Net", puis Valider => tracer targetNames (on doit voir ["salaire net"])
 - saisir 5000 => tracer foldedSteps (au lieu de ["salaire de base"] on s'attend à ["salaire net"])

On a pas le temps de réaliser ce test.

Mais on a découvert encore un bug:
- je saisis Brut, Net, 5000 - avant de cliquer Valider, je survole "Entrée"
- dans ce cas là quand je clique Valider ça ne valide pas, la question reste posée
- par contre quand je saisis à nouveau 5000 et que je Valide, le comportement observé est le nominal 🙃

**Comment by laem** [comment]
J'ai commencé une correction sur la branche `bug-net-brut-net`. Description dans le commit 4a5ddd80885c2ebd78fb1f71e2b3f2cf57563732.
Je suspecte qu'une solution propre puisse débloquer #146 ...
