### ISSUE TITLE
Mettre de l'ordre dans les mécanismes

### ISSUE THREAD

**Issue by laem** [betagouv/syso#154]
Un fichier ou un dossier (pour séparer par exemple le traitement JS du JSX d'affichage) par mécanisme. But : contribution plus facile. Pour ajouter un mécanisme ou en modifier un, il faut se taper un gros fichier, trouver le nom du mécanisme en anglais, etc. 
Documenter cette contribution (un mécanisme c'est une fonction d'évaluation, une fonction d'affichage, une fonction pour les variables manquantes, etc.)

**Comment by laem** [comment]
En profiter pour charger les données du versement transport à la demande. Il alourdit toute visite sur le site de 180k...

**Comment by laem** [comment]
À cette occasion, installer des contrôles de taille de l'application gzippée, comme suggéré par des experts internationaux [ici](https://github.com/betagouv/syso/pull/164#issuecomment-362412913). 
Nos librairies sont maintenant plus difficiles à optimiser que ce fichier JSON.

**Comment by jdesboeufs** [comment]
Pourquoi pas une API pour le versement transport ?

**Comment by laem** [comment]
Ce serait pratique et sympa d'enrichir etalab/api-communes en effet.
Il faudrait qu'on permette au mécanisme actuel de consommer un API à la place.

**Comment by jdesboeufs** [comment]
Déjà si tu éclates tes données par département ou par région, la poids devient plus digeste.

**Comment by laem** [comment]
Dans le cas de Paris et IDF les départements et taux transport doivent se recouper mais sinon ça n'a rien à voir, si ?
>  Ensuite un petit import dynamique et t'es bon.
Il faudrait quand même _promisifier_ tout notre moteur :sweat_smile: (ce qui est un très bon objectif à mon avis, ça favorise la délégation de responsabilité).

**Comment by johangirod** [comment]
Je pense que cet issue est couverte par #201 et #323 (je passe un petit coup de ménage sur le github)
