### ISSUE TITLE
Mauvaise typo dans le texte des SVG

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/syso#173]
Dans certaines images, comme https://embauche.beta.gouv.fr/dist/images/logo-simulateur.svg, le texte n'est pas converti en formes, donc si on n'a pas la fonte d'installée sur sa machine, ça affiche le texte en Times New Roman, ce qui n'est probablement pas l'effet désiré. Convertir le texte en formes pour éviter ce problème ? (et en profiter pour passer ces fichiers dans `svgo` ?)

**Comment by laem** [comment]
Merci pour ces conseils ! En effet, le 2300€ n'est pas bien rendu. Je m'en charge.
Au passage, si tu as de l'expérience dans l'art de faire marcher les SVG sur IE11, ça m'intéresse.

**Comment by mquandalle** [comment]
Le problème n'est plus présent sur le nouveau logo.
