### ISSUE TITLE
Traduction en anglais

### ISSUE THREAD

**Issue by laem** [betagouv/syso#179]
Comment faire la traduction ? 

Le script de la PR #176 utilise google traduction pour en suggérer. L'idéal est ensuite de tout repasser à la main, en s'équippant de linguee.fr et son frère [deepl](deepl.com), meilleure que Google.
Les forums de Wordreference sont excellents pour beaucoup de sujets.

Listons ici les questions de traduction en anglais. N'héistez pas à modifier directement ce commentaire.

- "net salary" peut-être compris comme net de toute taxe. En France, implicitement, "salaire net" = "salaire net de prélèvements sociaux"
- statut cadre. On serait tentés par "executive status" mais comme noté [ici](https://forum.wordreference.com/threads/cadre-entreprise.657897/?hl=fr), ça ne correspond pas. Je laisse tel quel.

Et puis les perles de traduction automatique :laughing:  : 
- statut cadre -> "status frame"

**Comment by Morendil** [comment]
Linguee est pas mal pour ça: https://www.linguee.com/english-french/search?source=auto&query=j%27ai+le+statut+cadre

Je choisirais quelque chose comme "management employee" ou "managerial position" mais il faudra peut-être préciser que le statut est lié à des cotisations plutôt qu'à des responsabilités.

**Comment by juliencarnot** [comment]
Sinon, il reste encore des humains qui font ça très bien! ;-) Sur une matière technique et pour un service qui a vocation à devenir très visible pour des employeurs étrangers, le coût d'une (ou de plusieurs) traductions pro peut se justifier...

**Comment by laem** [comment]
Je ferme en attendant des nouveaux développements.
