### ISSUE TITLE
Le fait d'avoir un résultat direct à la saisie du salaire n'incite pas à valider pour voir les questions suivantes

### ISSUE THREAD

**Issue by juliencarnot** [betagouv/syso#182]
À la première utilisation, j'ai cliqué sur SMIC, et vu un résultat s'afficher en bas. Il m'a fallu quelques secondes pour voir qu'il fallait cliquer sur Valider pour passer à la question suivante et affiner le calcul.

Une barre de progression/timeline dans les questions ou l'obligation de cliquer sur valider pour avoir un résultat serait peut-être utile, sauf si c'est juste moi qui ai marqué un temps d'arrêt sur cette première étape...

**Comment by juliencarnot** [comment]
erreur de repo: https://github.com/betagouv/cout-embauche/issues/290

**Comment by laem** [comment]
Merci pour le retour.

Peut être qu'une reformulation en "suivant" serait pertinente.

La barre de progression apparaît normalement après la première validation. 

Globalement, on travaille sur une branche à un redesign complet de la saisie du salaire (fusion de la barre de résultat et de la saisie salaire). Ça devrait régler ce problème :-)

**Comment by laem** [comment]
Je ferme, étant donné le redesign #191 qui a peut-être résolu le problème ou l'a en tout cas modifié.
N'hésite pas à rouvrir @juliencarnot ou en faire une nouvelle bien sûr.
