### ISSUE TITLE
un temps plein avec un net inférieur au SMIC est calculé par le simulateur

### ISSUE THREAD

**Issue by juliencarnot** [betagouv/syso#199]
![image](https://user-images.githubusercontent.com/3848493/38865427-065de8f8-423e-11e8-8345-f11a1e9f5cda.png)
Sur un temps partiel, il n'y a pas non plus de controle, un contrat de 32h à 600€ net passe également.

Une alerte et un calcul du salaire horaire pourrait être utile...

**Comment by laem** [comment]
Je ferme, ça rejoint une issue existante.
