### ISSUE TITLE
UI/UX problèmes

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#208]
Voici une petite liste de problèmes UI/UX que j'ai pu reperer en faisant un rapide tour.

### Communs

- [x] Lors du premier chargement, il y a un scintillement avec une version non stylisé de la page
- [x] Trop de différentes typographie. Il faudrait réduire drastiquement le nombre de styles utilisé. On y gagnerait énormément en clarté.
- [x] Il y a beaucoup de texte bleu non cliquable => confusion
- [x] Les inputs ne sont pas tous du même style. Il faudrait les uniformiser.
### Comprendre mes résultats
- [x] La police est très petite et les lignes sont peu aérées => pas très lisible
- [x] Valeur en bleue non cliquable => noir
- [x] Le bouton déplier est trop petit et trop clair. Pas du tout accessible.
- [x] Je ne sais pas à quoi correspondent les deux colonnes. Il n'y a pas de titre.
- [x] On parle de salaire total dans le tableau, mais de salaire chargé dans les objectifs
- [ ] ~~Lorsqu'on clique sur le bouton rechercher, on parle de règle. C'est la première fois que l'on rencontre ce mot, on ne sait pas trop à quoi il fait reference.~~
### Page règle
- [x] Bugs d'alignements et de margin
- [x] Le bouton reprendre la simulation => retour à la simulation ?
### Pendant la simulation
- [x] Moins de x question => bleu non cliquable
- [x] Les champs texte / nombre à remplir sont  à droite alors que les questions à choix multiples sont à gauche. Problème de cohérence
- [x] Les boutons oui non ne sont pas alignés sur la gauche (espace). 
- [x] Le bouton passer est bizarrement situé. J'hésiterai à cliquer dessus. Pourquoi ne pas dire clairement ce qu'il fait => mettre une valeur par défaut. D'autant plus que la valeur apparait dans "mes réponses" ensuite. Ca serait moins bizarre que de voir une question passée apparaitre dans mes réponses.
- [x] A chaque fois que l'on clique sur valider / passer, il y a un effet de scroll très désagréable.
- [x] Comprendre mes résultat et Modifier mes réponses devraient être cliquables
- [x] Le bandeau news devrait disparaitre pendant la navigation
- [x] L'icone "manuel" n'est pas très claire. Pourquoi ne pas prendre le classique point d'interrogation dans un cercle ? 
- [x] Lorsque l'on clique sur l'icone manuel, le texte d'aide ne s'affiche pas à coté => Allez retour visuel. On peut imaginer une petite infobulle. Ou alors une modale, je pense que ce serait plus adapté.
- [x] Sur des plus petits écrans, le CTA est en parti sous la ligne de flotaison, ce qui n'est pas tip top.
- [x] A la fin de la simulation, on a pas vraiment de retour visuel à part les boutons de feedback. Ajouter un texte simulation terminée ?

**Comment by laem** [comment]
Pour parler de règle, t'as une autre suggestion ? On l'utilise aussi sur la Home : "Toutes nos règles"

**Comment by johangirod** [comment]
Effectivement, après reflexion, je ne trouve pas mieux que règle :)

**Comment by johangirod** [comment]
Tout est résolu \o/
