### ISSUE TITLE
Agencement de l'application

### ISSUE THREAD

**Issue by laem** [betagouv/syso#211]
Il faut que l'on définisse, sépare mieux les différentes zones à l'écran.
Seule la zone de saisie des salaires en couleur est bien définie aujourd'hui. Modifier mes réponses, la question active, l'explication des résultats ne le sont pas. Idem sur les pages /règle.

@johangirod j'ai cassé ton commit 1b5857a825205c81d91017e6f975e072e3e781c7 pour pouvoir introduire la marianne en bas de l'écran d'acceuil, et aussi pour rendre visible l'explication dès la première estimation, pour pouvoir mettre en prod plus rapidement le redesign de #191 . C'est une fonctionnalité assez dificile à intégrer et maintenir, et je me demande si de meilleures délimitations visuelles ne seraient pas plus efficaces.

Exemple avec cette recherche Google : 

![screenshot_20180430-163434_chrome canary](https://user-images.githubusercontent.com/1177762/39432757-85da665a-4c94-11e8-8889-c0183c2492a6.jpg)

**Comment by johangirod** [comment]
@laem : on devrait pouvoir fermer cette issue suite à #256 et #222 ?
