### ISSUE TITLE
Forfait social

### ISSUE THREAD

**Issue by laem** [betagouv/syso#217]
C'est la seule "cotisation" qu'il nous manque.

https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-taux-de-cotisations/le-forfait-social/le-forfait-social-au-taux-de-8.html

Le forfait social a des taux différents sur plusieurs assiettes. La plupart ne nous concernent pas (encore), sauf celui assis sur les avantages sociaux : complémentaire santé et prévoyance obligatoire pour les cadres.

Il est d'ailleurs le sujet de discussions politiques en ce printemps 2018.

**Comment by mquandalle** [comment]
Clôturé par #231
