### ISSUE TITLE
Temps partiel : incompréhensions ?

### ISSUE THREAD

**Issue by laem** [betagouv/syso#221]
Certains utilisateurs ont cette première compréhension, d'autres non. Nous avons implémenté cette dernière, mais eu beaucoup de retour négatifs.
---
https://mail.google.com/mail/u/1/#inbox/WhctKJVRNKSLjxLtxbZVVwVhzkhJfBBprNzcvCsSpvfSLWGsnRltCVsCSdDrSTNDWjVDwtl

**Comment by johangirod** [comment]
Il y a encore beaucoup de retours d'incompréhension.

Je viens d'avoir une idée qui pourrait résoudre le problème : 
Lorsque l'utilisateur saisi "temps partiel", une nouvelle ligne objectif apparait dans le simulateur : "équivalent temps plein". La personne pourrait alors selectionner l'objectif pour bloquer la valeur et voir comment le nombre d'heure influe sur les autres valeurs...

On pourrait reprendre le même principe pour les heures supp

A réflechir.

**Comment by mquandalle** [comment]
La ligne « équivalent temps plein » a été implémentée est facilite la compréhension. Il reste encore des choses améliorables, mais on peut ouvrir des issues dédiées.
