### ISSUE TITLE
Amélioration visuelle des pages /règles

### ISSUE THREAD

**Issue by laem** [betagouv/syso#222]
Ca concerne d'un côté le zonage des éléments de cette page : #211 .

Et de l'autre une amélioration du JSX produit par les mécanismes. 

Exemple : **les composantes** sont aujourd'hui alignées horizontalement, c'est une catastrophe (notamment sur mobile). Il faudrait les transformer en sections à la suite verticalement et potentiellement repliables et introduites par un texte du genre : "Cette règle est la somme de deux composantes.".

Autre exemple, le mécanisme courant de barème gagnerait à être mieux expliqué, par exemple en calculant pour chaque tranche la valeur si cette tranche est active.

:loudspeaker:  :loudspeaker: 

Une fois cette passe graphique réalisée, je pense que l'on pourrait **commencer une communication axée sur l'explication des algorithmes de l'administration**. Voilà votre fiche de paie expliquée, de ces lignes aux  barème et conditions d'application qui se cachent derrière, comprenez comment tout celà est calculé avec les données de votre situation. 

https://mobile.twitter.com/emmanuelmacron/status/979393260538953729
https://mobile.twitter.com/villanicedric/status/979369490306748417

Un blog post visuel sur le sujet serait génial.

**Comment by johangirod** [comment]
Une petite todo : 
## Rendre moins complexe la page au premier coup d'oeil
- [ ] Réduire le nombre de couleurs différentes
- [ ] Réduire le nombre de taille de police différentes
- [ ] Enlever le cadre bleu
- [ ] Rendre le namespace plus petit et plus discret
- [ ] Déplacer le bouton recherche
- [ ] Zoner / changer le titre et la position des sections calcul et applicabilité
## Rendre l'explication du calcul plus compréhensible
- [ ] Changer le layout du mécanisme de composante vers un layout en ligne (plutot qu'en colonne)

**Comment by johangirod** [comment]
Fixed by #279 
Open #349
