### ISSUE TITLE
Nouvelle vue "où va mon argent" ?

### ISSUE THREAD

**Issue by laem** [betagouv/syso#223]
Aujourd'hui notre grille de résultats "Comprendre mes résultats" est un mélange de la feuille de paie et d'une vue synthétique mais intéractive.

Il serait mieux d'avoir deux onglets, l'un qui est une vue fidèle à la fiche de paie, et l'autre nouvelle.

Elle expliquerait très simplement et visuellement (https://www.emojione.com/emoji/v3) dans quelles grandes catégories de risque les cotisations (auquelles les réductions auront été retranchées) vont. Dans cette vue, pas de CSG : elle peut être subdivisée en plusieurs postes plus parlants (maladie, famille).

Elle ignorerait la distinction presque artificielle "cotisations employeur vs salarialé", et permettrait ainsi de se rendre compte notamment que l'essentiel de la fiche de paie... c'est pas "pour payer les fonctionnaires" mais du salaire futur :bank:  pour nos 70 ans :smile: .

**Comment by johangirod** [comment]
Fixed by #248
