### ISSUE TITLE
Salaire net après impôts

### ISSUE THREAD

**Issue by laem** [betagouv/syso#225]
La réforme de l'impôt à la source introduira _sur les fiches de paie_ un nouveau salaire. Il faut qu'on l'intègre avant l'automne.

On introduirait une version ultra simple à calculer : l'impôt neutre. Il est pertinent et nous évite de dérouler la complexité de la situation du ménage et des rémunérations autres que le salaire.

Il remplacerait alors le 4ème élément de l'écran d'accueil, les aides employeur, que l'on intégrerait intelligemment dans le "salaire chargé", auquel elles se retranchent (elles en sont aujourd'hui trop éloignées). 

Exemple artisanal mais qui me semble intuitif et suffisant pour attirer l'attention : 

**Salaire chargé** :  3500 €  :heavy_minus_sign:    180 € :gift: :hourglass_flowing_sand:

**Comment by johangirod** [comment]
Duplicate of #224
