### ISSUE TITLE
Saisie difficile sur iOS/Chrome

### ISSUE THREAD

**Issue by Morendil** [betagouv/syso#233]
J'ai voulu montrer le produit sur mon téléphone (whatismybrowser.com/w/8676RG4) et ce n'était pas très convaincant, quand on ferme le clavier virtuel après la saisie d'un salaire il revient aussitôt et on ne voit pas les résultats. Je ne sais pas si c'est une régression ou à quel changement ça peut être lié…

**Comment by johangirod** [comment]
Effectivement, testé avec Browserstack, lorsqu'on clique sur le bouton "terminé" en haut à droite du clavier, le clavier se repli pour se rouvrir juste après. 

J'ai enqueté pendant 2 heures ce matin, pas évident de trouver où est le problème. Je sais que c'est du à ce commit 7ab7c6c7eb8b21d6d96d501f708d88acd323f6ce. J'ai testé plusieurs hypothèse mais aucune n'explique ce comportement.

- Ce n'est pas du à un autoFocus qui se réactive
- Ce n'est pas du à un defocus + focus du champs
- C'est du à une modification du `onChange`
=> Prochaines pistes : redux-form

**Comment by johangirod** [comment]
Pour information, ce bug (non bloquant) concerne pour l'instant <1% des visiteurs
