### ISSUE TITLE
Problèmes pages /règle

### ISSUE THREAD

**Issue by laem** [betagouv/syso#236]
Suite à #232 

- [ ] le :heavy_check_mark: [ici](https://embauche.beta.gouv.fr/règle/contrat-salarié--AGFF) apparaît en rouge, c'est perturbant
- [x] maintenant que les variables ont le style d'un lien, je pense qu'il faut enlever le texte `Cliquez sur chaque chaque valeur pour comprendre`

----------------------

![screenshot_20180523-160305_chrome canary](https://user-images.githubusercontent.com/1177762/40429392-e79ae70a-5ea2-11e8-857c-d6249e9260db.jpg)

**Comment by johangirod** [comment]
@laem: Bizarre, sur firefox, archlinux il est bien en vert...
Tu navigue d'où ? http://whatismybrowser.com/

**Comment by johangirod** [comment]
Visiblement, c'est le cas de chrome android

**Comment by johangirod** [comment]
Résolu par #256
