### ISSUE TITLE
Ajout du salaire net imposable

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#240]
La plupart des fiches de paies incluent le `salaire net imposable`. Celui ci diffère du salaire net car certaines cotisations ne sont pas déductibles de l'impots sur le revenu. Il s'agit par exemple de la CSG non deductible, de la CRDS ou encore du remboursement du transport ou d'autres avantages salariés.

Je pense qu'il devrait être possible de l'avoir également dans notre simulateur. De plus, il sera forcément nécessaire pour #224. On peut imaginer une nouvelle variable : `cotisation non déductible`.

`salaire net` = `salaire net imposable` - `cotisation salariales (non déductible)`
`salaire net imposable` = `salaire brut` - `cotisation salariales (déductibles)`

Avec 
`cotisations salariales` ayant une composante déductible et une composante non déductible.

https://www.compta-online.com/comment-calculer-le-net-imposable-du-salarie-ao1082

**Comment by Morendil** [comment]
La syntaxe `variable (composante)` pour filtrer les composantes ne fonctionne pour l'instant que pour le champ "dû par", il faudrait en généraliser la syntaxe.

**Comment by johangirod** [comment]
Implémenté dans #256
