### ISSUE TITLE
Supprimer la notion d'avantages salariés

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#242]
### Problème
J'ai beau chercher, je ne trouve pas dans la loi la notion d'`avantages salariés`, telle que l'on peut la trouver [dans notre simulateur](http://localhost:3000/r%C3%A8gle/contrat-salari%C3%A9--avantages-salari%C3%A9). 

Et nulle part n'est fait mention que la part salariale de la cotisation pour la mutuelle, ou que la prévoyance obligatoire pour les cadre est considérée comme un avantage salarié pris en compte dans le calcul du salaire brut [comme défini dans le simulateur](http://localhost:3000/r%C3%A8gle/contrat-salari%C3%A9--salaire-brut)

### Ce que dit la loi
D'après ce que je peux lire (cf [ici](https://www.service-public.fr/particuliers/vosdroits/F2301), [là](http://travail-emploi.gouv.fr/droit-du-travail/remuneration-et-participation-financiere/remuneration/article/le-salaire-fixation-et-paiement) ou encore [là](http://dsn-info.custhelp.com/app/answers/detail/a_id/640/~/salaire-de-base)) on aurait : 
 
`salaire brut` =  `salaire de base` + `heures supplémentaires` - `retenues` + `indémnités` + `primes` + `avantages en nature`
`retenues` = `absence maladie` + `absence congé payé` + `absence congé sans solde` 
`indémnités` = `indémnité congé payé` + `indémnité journalière de sécurité sociale (IJSS)`+ `indémnité compensation congés payés` + ...
`primes` = `primes convention collective` + `prime exceptionnelle` + ...
`avantages en nature` = `voiture` + `ticket restau financé à plus de 60% de la valeure du titre` + ...

### Proposition
- Supprimer la notion d'avantage salarié. Avoir uniquement la notion de salaire de base. 
- Changer le calcul (apparemment inexact) du salaire brut par
    `salaire brut` = `salaire de base` + `indémnité congé sans solde` + `prime de fin de contrat CDD`

**Comment by laem** [comment]
La part salariale de la complémentaire santé n'est en effet pas un avantage salarié, et donc pas dans le salaire brut. Le site est trompeur car il  ne montre pas le `(employeur)` qui suit `complémentaire santé` dans les avantages... #244.
C'est le cas par contre de la part employeur et de la prévoyance obligatoire cadre qui est uniquement patronale.

Ces deux éléments sont les "avantages sociaux". C'est en réalité des cotisations sociales mais qui vont à des caisses privées dans un marché concurentiel. Ce sont des avantages car l'employeur est tenu d'en payer une partie. On pourra dire que ça change rien, car l'employeur peut prendre en compte ces avantages pour promettre un salaire. Sauf qu'il ne peut pas proposer un salaire _de base_ inférieur au SMIC. Donc si la complémentaire santé qu'il propose (et qui est obligatoire pour le salarié) n'est pas une arnaque qui l'obligerait à payer trop de sa poche (mais au maximum 50%), le salarié a reçu un avantage.

**Comment by johangirod** [comment]
Ok je viens de comprendre, c'est une manière de marquer la différence entre une "cotisation", universelle et gérée par le public, et les "avantages sociaux" qui correspond à leur pendant privé et spécifique à l'entreprise.

Mais encore une fois, je ne suis pas sûr que notre modèle soit juste vis à vis de la définition du `salaire brut`. 

Si je prends par exemple sur la fiche de paie suivante : 
![35h-01-2015](https://user-images.githubusercontent.com/1775934/40831925-8cd8ffde-658a-11e8-8686-6b46b3bc1f9d.jpg)

On voit que le salaire brut (pris comme assiette de base) est considéré comme `salaire de base` + `prime et indémnité` + `retenues et heures supplémentaires` + `avantages en nature`. 
 
Vue que la mutuelle ne rentre pas dans l'assiette des cotisations (à la différence des autres avantages en nature), elle ne doit pas faire partie du salaire brut. En revanche, elle doit être ajoutée (comme la prévoyance et autre retraite supplémentaire) pour calculer le salaire net imposable.

Si on veut rester fidèle aux fiches de paie, c'est une (petit) changement à faire (ça revient grosso modo à déplacer la ligne "avantage salarié" du début à la fin :) )

**Comment by laem** [comment]
Je reste convaincu que c'est du salaire brut, même si en effet c'est une notion mal définie.
Ce qui est sûr, c'est que c'est du salaire : des € ou un service payé en l'échange du travail fourni. C'est aussi du brut car c'est avant retranchement des cotisations sociales. 

Comme tu le remarques, la plupart des cotisations ne sont pas assises dessus, et ça peut être une raison de la séparer du salaire brut. Mais c'est quand même le cas de la CSG, CRDS, du forfait social. Pour moi c'est une partie du salaire brut qui bénéficie d'un régime particulier : exempté de la plupart des cotisations sociales.

C'est pour ça que nous avons la variable ["assiette des cotisations sociales"](https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/la-base-de-calcul/assiette-des-cotisations-dassura.html) : chez l'URSSAF on ne verra pas souvent la notion salaire brut, je pense que c'est parce qu'elle est trop mal définie. 

Du coup, on pourrait rapprocher les cotisations de santé privées des cotisations sociales et donc dire que leurs composantes employeur ne sont pas du salaire brut, même si contrairement aux part employeur des cotisations sociales elles sont ensuite intégrées dans d'autres taxes dont les impôts.

**Comment by johangirod** [comment]
> Du coup, on pourrait rapprocher les cotisations de santé privées des cotisations sociales et donc dire que leurs composantes employeur ne sont pas du salaire brut, même si contrairement aux part employeur des cotisations sociales elles sont ensuite intégrées dans d'autres taxes dont les impôts.

Exactement. En tout cas c'est ainsi que c'est présenté sur une fiche de paie classique. 

En revanche, pour ne pas abandonner l'idée de séparer sur le principe la cotisation à un organisme publique au paiement à une structure privée, on peut réintroduire la séparation au niveau du du salaire net

### Proposition 
`salaire brut` = `salaire brut de base` + `part variable`
`salaire net` = `salaire brut` - `cotisations salariales` - `avantages sociaux (salarié)`
`salaire net imposable` = `salaire net` + `avantages sociaux (employeur)`
`salaire net à toucher` = `salaire net` - `avantages en nature` + `remboursements de frais`
`avantages sociaux` = `complémentaire santé` + `prévoyance obligatoire cadre`

**Comment by johangirod** [comment]
Résolu dans #256
