### ISSUE TITLE
Erreur de rendu sans affichage d'un message pour l'utilisateur

### ISSUE THREAD

**Issue by Flightan** [betagouv/syso#260]
Quand je clique sur le "bouton" pour afficher l'explication d'un terme, je tombe sur une page vierge sans possibilité de revenir en arrière et sans explications.

<img width="518" alt="screen shot 2018-06-19 at 23 44 21" src="https://user-images.githubusercontent.com/1475946/41625932-e1b952ee-741a-11e8-8fd4-35b062ae047b.png">
<img width="518" alt="screen shot 2018-06-19 at 23 44 32" src="https://user-images.githubusercontent.com/1475946/41625931-e18504b2-741a-11e8-80fd-b4024d072af6.png">
<img width="518" alt="screen shot 2018-06-19 at 23 44 39" src="https://user-images.githubusercontent.com/1475946/41625930-e16e5bea-741a-11e8-8d91-6dded973d7cb.png">

**Comment by laem** [comment]
Merci @flightan ok corrige aujourd'hui.

(On a revu entièrement notre state redux, bougé la plupart dans les sélecteurs, ça a cassé la gestion de cette boîte d'explication)

**Comment by johangirod** [comment]
Résolu par e16ef7e975d8c13f5b994c0c122ee85cbccd2077
