### ISSUE TITLE
Entrer une valeur à plus de 3 chiffres fait disparaître l'intégralité de la page web

### ISSUE THREAD

**Issue by MattiSG** [betagouv/syso#275]
Sur infrance.org ou sur embauche.beta.gouv.fr, si j'entre une valeur à plus de trois chiffres, la page devient blanche et je dois la recharger.

![simulateur embauche2](https://user-images.githubusercontent.com/222463/42297042-dcf1e922-8047-11e8-84a9-d2264e64c2a9.gif)

**Comment by laem** [comment]
Merci pour le retour ! C'est quel navigateur ?

**Comment by laem** [comment]
Pas possible de la reproduire, vieille _issue_, et c'est le genre d'erreur que Sentry devrait nou remonter.
