### ISSUE TITLE
proposer statut "gerant SAS assimilé salarié"

### ISSUE THREAD

**Issue by nbald** [betagouv/syso#302]
Salut

Il serait sympa de pouvoir calculer le coût de la rémunération d'un gérant d'une SAS assimilé salarié. Je pense que le calcul n'est pas très différent. Quelques cotisations en moins (chomage…)

**Comment by laem** [comment]
Bonjour, merci pour ton retour ! Bonne nouvelle : c'est commencé ici #281 et pas loin d'être terminé. A priori on le mettra non pas sur embauche.beta.gouv.fr mais sur un nouveau site (en anglais dans un premier temps) qu'on va lancer qui explique comment créer sa société sous l'angle de la sécurité sociale, donc un bon endroit pour intégrer cette notion d'assimilé salarié.

**Comment by laem** [comment]
Commencé dans #281 . Reste : 

- [ ] Résoudre les problèmes du mécanisme `une possibilité`, ou s'en passer en changeant `type de contrat` en un booleén `CDD`
- [ ] faire en sorte que dans le simulateur d'embauche assimilé salarié = non
- [ ] ajouter une page à infrance avec assimilé salarié = oui dans la suite de la société SASU qui permet de simuler le salaire du patron
- [ ]  l'étendre aux autres situations qui permettent le statut d'assimilé salarié (ex. EURL gérant minoritaire)
- [ ] loudspeaker tester une URL simulation assimilé salarié avec tous les indeps en SASU autour de nous

**Comment by johangirod** [comment]
Disponible sur https://demo.mon-entreprise.fr/sécurité-sociale/assimilé-salarié
Et très bientôt sur https://mon-entreprise.fr
