### ISSUE TITLE
Ajouter des mentions légales

### ISSUE THREAD

**Issue by guillett** [betagouv/syso#311]
Template

>Mentions légales  Urbaclic
>
>Editeur
>Incubateur des services numériques, Direction interministérielle du numérique et du système d'information et de communication de l'Etat (DINSIC), Services du Premier ministre.
>
>Directeur de la publication
>M. Henri Verdier, Directeur interministériel du numérique et du système d'information et de communication de l'Etat (DINSIC).
>
>Prestataire d'hébergementa
>OVH
>RCS Roubaix – Tourcoing 424 761 419 00045Code APE 6202AN° TVA : FR 22 424 761 419Siège social : 2 rue Kellermann - 59100 Roubaix - France
>
>Contactez-nous : <email>

**Comment by johangirod** [comment]
On peut reprendre tel quel ? (sauf pour l'hébergement dans notre cas, à changer pour netlify)

**Comment by guillett** [comment]
Oui :)

**Comment by laem** [comment]
Les mentions sont obligatoires ?

**Comment by guillett** [comment]
Oui
