### ISSUE TITLE
Uniformisation "data-couleur" et "data-lang"

### ISSUE THREAD

**Issue by BorisLeMeec** [betagouv/syso#338]
Pourquoi avoir une des variables en anglais et l'autre en français ?
Plus logique de faire [`data-color` et `data-lang`] ou [`data-langue` et `data-couleur`], non ?

**Comment by laem** [comment]
Merci pour la remarque ! 
Techniquement ce n'est pas un problème de langage, mais plutôt d'abbréviations : couleur n'est pas écourté parce que `coul` n'évoque rien, alors que `lang` est compréhensible. 

Mais je suis d'accord avec toi, ça n'a aucun intérêt, et mieux vaut avoir `data-langue`.

Dans le même genre, dans le code se baladent des `colour` alors que la propriété CSS est `color`... Là aussi une mauvaise décision.

**Comment by BorisLeMeec** [comment]
Dans l'idée j'aurais plutôt tout mit en anglais ;)
Je peux faire une PR si il faut

**Comment by laem** [comment]
Malheureusement, impossible de changer ce bout de code : c'est notre lien avec les intégrations en iFrame des partenaires (pôle-emploi par exemple, mais aussi 30 autres), et ça risque d'être très compliqué de tous les faires changer ces attributs...

**Comment by BorisLeMeec** [comment]
C'est peut être pas ouf, mais accepter les 2, et dans la doc et les exemples mettre le bon, ça fera une sorte de rétro comptabilité
