### ISSUE TITLE
Suppression de la cotisation salariale chômage au 1er octobre

### ISSUE THREAD

**Issue by laem** [betagouv/syso#351]
La cotisation salariale d’assurance chômage fixée à 0,95 % depuis le 1er janvier 2018 est supprimée au titre des périodes courant à compter du 1er octobre 2018.

**Comment by laem** [comment]
@benjello

**Comment by benjello** [comment]
Merci @laem !
On l'avait [déjà](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/parameters/cotsoc/sal/commun/assedic.yaml)
