### ISSUE TITLE
Lorsque l'on clique sur "tout supprimer", la simulation garde la valeur des précédentes réponses

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#354]
Lorsque l'on clique sur `Modifier mes réponses` puis sur `Tout supprimer`, la page revient à l'état initial (juste le simulateur), mais pas les calculs. Lorsque l'on explore les règles, on s'aperçoit que les anciennes valeurs des réponses aux question n'ont pas été remplacée par les défaut.

On s'attendrait à repartir d'une page blanche plutôt que des précédentes valeurs.  C'est le cas du choix de la localisation par exemple.

D'autre part, lorsque l'on clique sur `Faire une simulation personalisée` après avoir supprimer ses réponses, la première question posée est celle du `Salaire net` (!)

**Comment by laem** [comment]
Bien vu !

**Comment by johangirod** [comment]
Fixed by #360
