### ISSUE TITLE
Problèmes d'affichage de la page impôt sur le revenu

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#355]
![screenshot_2018-09-11 impot neutre sur le revenu](https://user-images.githubusercontent.com/1775934/45349129-c3e16400-b5b0-11e8-8df9-9b70b6f09ba9.png)

Cette page a plusieurs problèmes : 
- Le style de la liste Si / Sinon, avec les bullet point est assez brouillon et surtout peu lisible
- Le département par défaut (Finistère) est assez incompréhensible
- La valeur par défaut du barème est déplacée tout en bas

### Propositions
- [x] Déplacer la valeur par défaut en haut de la liste
- [x] Refermer les explications des branches non active (avec possibilité de les ouvrir au click)
- [x] Utiliser les symbole x / v au lieu du surlignage pour plus de cohérence
- [x] Créer une valeur par défaut du département se nommant `Non renseigné`, un code commune à `Non renseigné` qui pointe vers une valeur moyenne du versement transport. (#356)

**Comment by johangirod** [comment]
Au passage, le surlignage abouti a des trucs qui piquent un peu les yeux dans certains cas : 
![screenshot_2018-10-02 contribution supplementaire a l apprentissage](https://user-images.githubusercontent.com/1775934/46366131-ac127280-c67a-11e8-8d7d-7d876254ba1b.png)

**Comment by laem** [comment]
En attendant de réfléchir au repliage des branches, j'ai rendu ce surlignage jaune moins invasif sur #400
