### ISSUE TITLE
Webpack-serve déprécié

### ISSUE THREAD

**Issue by laem** [betagouv/syso#375]
@johangirod on s'est fait avoir :smile: 

Si tu as un peu de temps pour revenir en arrière... ça s'est passé dans ce commit, et j'ai un peu de mal à voir ce qu'il suffit de faire pour revenir à webpack-dev-ser.

https://github.com/betagouv/syso/commit/0e028cc843147b01a7e2efc34d477020e9d4d346

**Comment by johangirod** [comment]
Oupsy, j'imagine que c'est le genre de chose qui peut arriver en utilisant des librairies un peu jeunette :sweat_smile: 

Dommage, elle était plein de promesse... Va pour un retour à webpack-dev-server, ça ne devrait pas être très compliqué.
