### ISSUE TITLE
Mettre à jour la V1 avec la dernière version d'OpenFisca

### ISSUE THREAD

**Issue by Morendil** [betagouv/syso#38]
- [X] "Smoke test" manuel en local 
- [ ] Mise à jour de la prod

J'ai déjà effectué un test rapide en déroutant un serveur local vers api.openfisca.fr et ça semble marcher correctement. Je ne sais pas si des tests plus poussés sont nécessaires. En tout état de cause il convient d'attendre une version d'OpenFisca intégrant les évolutions du 1er juillet.

**Comment by laem** [comment]
Dans ton test, salaire net -> salaire brut a du casser non ? 

Normalement ça devrait bien se passer en jouant simplement le script Ansible de mise à jour d'OpenFisca :pray:

**Comment by Morendil** [comment]
C'était vraiment un "smoke test", je ne suis pas allé jusqu'à titiller le calcul net->brut.

**Comment by laem** [comment]
Fait. Nous avons décidé d'abandonner la fonctionnalité d'inversion, maintenant disponible ici.
