### ISSUE TITLE
Intégrer les heures supplémentaires

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#402]
Dans certains cas, l'entreprise peut bénéficier d'un aménagement des horaires pour le temps de travail de ses salariés, supérieur à celui des 35h. Il faudrait donc pouvoir intégrer le calcul des heure supplémentaires dans le simulateur.

Le souci, c'est que les taux varient en fonction: 
- Du nombre d'heure supplémentaire consécutive dans la semaine (taux majorés)
- De la convention collective (par défaut, 25% et 50%)  

Dans l'absolu, il faudrait trouver un moyen de spécifier rapidement et simplement ces différents taux, et de specifier combien d'heure supplémentaires lui sont associés. 

Et c'est la que le bât blesse, je ne vois pas comment cela est possible dans notre moteur aujourd'hui. Il faudrait pouvoir ajouter dynamiquement des règles de calculs suite à une question. 

On peut en revanche implémenter très simplement les taux par défaut (25% et 50%) sans problème.

-----
https://mail.google.com/mail/u/1/#inbox/FMfcgxwChSJjtFWKChdWTLFkSNWsnPtC
----
https://mail.google.com/mail/u/1/#inbox/FMfcgxwChSJkWPJWZRtxNsCHwTWbzTMT
---
https://mail.google.com/mail/u/1/#inbox/FMfcgxwChSKrcqTNbVwBNwJFfqbsfhhL
---
https://mail.google.com/mail/u/1/#inbox/WhctKJVRNKKpdTsLHRgkTlgVPJVVQQzLblBQvZppxTmWbdddPrpVJQPJmtvKNkGVjXLZsTG

**Comment by laem** [comment]
Heures supplémentaires et temps de travail des salariés, c'est le même sujet ?

**Comment by johangirod** [comment]
D'après ce que j'ai compris, le volume horaire peut-être modifié via plusieurs moyens : 
- Via un aménagement du temps de travail qui lisse sur un temps long les 35h (2 mois à 39h et 2 mois à 31h par exemple)
- Via le rattrapage des heures effectué avec des journée des repos
- Via les heures supplémentaires.

Sur ces trois solutions, seule la dernière impact directement les finances de l'entreprise, et la fiche de paie. https://www.service-public.fr/particuliers/vosdroits/F75. Dans les deux autres cas, la rémunération reste la même.

Après, j'ai pu louper quelque chose, mais en tout cas, la question des heures supplémentaire interessera du monde.
https://www.service-public.fr/particuliers/vosdroits/F2391

**Comment by laem** [comment]
La question que je me pose, c'est quand on proratise les montants du calcul (SMIC, plafond sécu) par nb d'heures / 35, comment faut-il le faire dans chacun de ces cas ?
Je me rappelle que le calcul dans OpenFisca n'était pas clair ni documenté...

**Comment by johangirod** [comment]
Les heures supplémentaires ont l'air d'ouvrir le droit à une nouvelle exonération : 
https://www.urssaf.fr/portail/home/employeur/beneficier-dune-exoneration/exonerations-generales/la-deduction-forfaitaire-patrona.html

**Comment by johangirod** [comment]
Autre remarque sur l'aménagement du temps de travail et heure supplémentaires : la période de référence à partir de laquelle sont calculées les heures majorée (25% puis 50%) est modifiable par les convention et accord d'entreprise. Par défaut d'une semaine, elle peut être étendue jusqu'à 3 ans. 
A priori, l'impact obtenu par cet allongement devrait être un moindre recours aux heures supplémentaires fortement majorée.

**Comment by johangirod** [comment]
En vrac : 
- Les heures supplémentaires sont interdites pour les moins de 18 ans
- Les heures complémentaires n'ont pas les même taux de majoration
- Mensuellement, la durée légale du travail est : `(35 heures * 52 semaines)/12 mois = 151.67 heures`
- A l'année en comptant les congé payés, jours fériés et journée de solidarité, la durée légale du travail à l'année est 1607h (chiffre officiel)
- Pour la semaine : la durée maximale absolue est 48 heures. Ou 44 heures pendant 12 semaines consécutives (c'est la durée maximale moyenne)

**Comment by johangirod** [comment]
Différence entre RTT et Récupération compensateur de récupération (RCR) : 
- L'acquisition de RTT résulte d'un accord d'entreprise organisant la durée du travail sur une période supérieure à la semaine et au plus égale à l'année
- Les repos compensateur résultent d'un accord d'entreprise. Le paiement des heures supplémentaires est alors remplacé par du repos compensateur d'une durée équivalente, c'est à dire incluant les majorations légales ou conventionnelles.

**Comment by johangirod** [comment]
Ne pas oublier [la déduction forfaitaire pour les cotisations patronales](https://www.urssaf.fr/portail/home/employeur/beneficier-dune-exoneration/exonerations-generales/la-deduction-forfaitaire-patrona/heures-et-remunerations-concerne.html)

**Comment by johangirod** [comment]
La circulaire qui précise les modalités de calcul : http://circulaire.legifrance.gouv.fr/pdf/2019/04/cir_44492.pdf

**Comment by johangirod** [comment]
Exemple de fiche de paie détaillé avec heures supplémentaires : 
https://www.compta-online.com/heures-supplementaires-2019-la-circulaire-est-publiee-ao3468#NULL

**Comment by johangirod** [comment]
En fait le sujet de la defiscalisation est épineux. Une note de la DSN précise son application : 
https://dsn-info.custhelp.com/app/answers/detail/a_id/2110

> En principe, l’employeur doit distinguer d’une part le salaire brut et d’autre part les heures supplémentaires pour en déterminer séparément le montant imposable ou exonéré, ce qui implique de déterminer un plafond spécifique à chaque salarié en fonction des cotisations non couvertes par la réduction applicable au montant brut versé.

> En pratique, il est admis que l’employeur applique la méthode suivante.

> Cette méthode consiste à déduire de la rémunération brute totale (salaire en brut et heures supplémentaires en brut) l’intégralité des cotisations et contributions sociales déductibles (y compris la CSG et la CRDS), diminuée de la réduction proportionnelle de cotisations salariales sur les heures supplémentaires et majorée de la CSG non déductible de la CRDS.

> Le montant ainsi obtenu se voit diminué du montant de la rémunération brute des heures supplémentaires exonérées diminué de la fraction de la CSG déductible afférente à cette rémunération dans le respect de la limite de 5 000 € nets par an.

> Avec cette méthode, dans le cas où le taux moyen de cotisations et contributions salariales déductibles – hors CSG et CRDS – afférent aux heures supplémentaires est supérieur au taux maximum de la réduction proportionnelle de cotisations salariales, le reliquat est déductible de la rémunération brute imposable.

> Le montant brut du plafond est obtenu en réintégrant la part déductible de la CSG. Ainsi, ce plafond est égal au montant net imposable des heures supplémentaires de 5 000€ auquel s’ajoute la part de la CSG déductible assise sur ces heures exonérées soit 5 358 €. Le détail du calcul est présenté ci-après.

> Le plafond brut d’exonération des heures supplémentaires est calculé de la manière suivante :

> `5000 / (1 – (98,25/100) x (6,8/100)) = 5357,96` arrondi à `5 358 €`

**Comment by mquandalle** [comment]
Résolu 🎉
