### ISSUE TITLE
Champs de recherche des commune non sensible aux tirets '-' 

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#403]
Il faudrait faire en sorte que le champs de recherche des communes ne soit pas exigeant vis à vis de l'orthographe des tirets dans le nom des villes. 

Exemple : 
saint denis => Saint-Denis
saint romain de lerps => Saint-Romain-de-Lerps

**Comment by laem** [comment]
C'est du côté de l'API Géo non ? 
A moins que l'on ajoute nous même des tirets où il y a un espace, mais ça me semble risqué.

**Comment by johangirod** [comment]
Ca vient de notre composant select. Je prends.

**Comment by laem** [comment]
il y a eu une nouvelle version majeure du composant, n'hésite pas à faire le changement si c'est pas trop lourd.

**Comment by johangirod** [comment]
J'ai vu ça, mais je me suis dit que ce n'était pas prioritaire pour l'instant...
