### ISSUE TITLE
Simulation de cotisations pour les indépendants

### ISSUE THREAD

**Issue by laem** [betagouv/syso#423]
Pour que la page /secu prennent tous principaux cas possibles en compte :  micro- Indep - Assimilé salarié (- salarié). 
- Implémenter les cotisations : 
  - professions libérales
 https://www.service-public.fr/professionnels-entreprises/vosdroits/F31233
  - commerçants, artisans et industriels
https://www.service-public.fr/professionnels-entreprises/vosdroits/F23890

Beaucoup de choses sont communes, les différences sont des exceptions. Et pour les micro ?

- Se charger de l'aiguillage entre les régimes
Voir la section "Personnes concernées" sur le 1er lien S-P plus haut.
On le fait déjà dans le choix de la forme juridique. Mais sur le page /secu, il faudrait déterminer le régime sans poser les autres questions inutiles concernant la forme juridique elle-même. 

- 2ème temps : expliquer les cotisations forfaitaires de début d'activité pour les indeps, *schématiquement* et *avec les données saisies*. Avertir du risque de ne pas provisionner les cotiz futures.

-

**Comment by mquandalle** [comment]
Implémenté
