### ISSUE TITLE
Reprendre le bouton "mes réponses"

### ISSUE THREAD

**Issue by laem** [betagouv/syso#448]
Le transformer en un gros bouton "Ma situation", qui serait dispo sur toutes les pages, qui au clic afficherait toutes les valeurs par défaut dans un section, et pouvoir les modifier directement (utilisation experte).

**Comment by johangirod** [comment]
Je copie ici les remarques issues de la PR #502 

> L'utilisateur qui découvre le simulateur est donc totalement guidé vers une simulation complète, pas à pas, dans l'ordre d'importance des questions. C'est notre cible principale, il ne faut pas la perdre.

> Pour satisfaire l'utilisateur expert, au-dela d'une sauvegarde améliorée des données, nous pouvons lui donner la possibilité de répondre à la demande à n'importe quelle question via un champs de recherche.

> On aurait alors la première question qui apparaîterait automatiquement, et ainsi de suite.
Pour remplacer les raccourcis, faire remarquer le bouton "ma situation" ou le reformuler différemment : il permettra aux experts de choisir à quelle question ils veulent répondre. Il faut alors y afficher les questions qui n'ont pas de missingVariables : les question prioritaires qui ne dépendent pas d'une autre réponse. On peut aussi y apporter un semblant d'ordre en affichant leur espace de nom (contrat de travail, entreprise et bientôt situation personnelle).

**Comment by laem** [comment]
Retour utilisateur qui ne trouve pas la question qui répond à son besoin : 

> manque la case ou faire bénéficiaire de l'ACCRE

**Comment by johangirod** [comment]
L'issue #583 reprend ces éléments en apportant des pistes de solutions, je propose qu'elle prenne le pas sur celle-ci.

**Comment by mquandalle** [comment]
Ah oui pardon j'avais pas vu 😀
