### ISSUE TITLE
Les contrôles sont évalués même quand la branche à laquelle ils appartiennent est désactivée

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#452]
![screenshot_2019-01-29 micro-entreprise cotisations et protection sociale mon-entreprise fr](https://user-images.githubusercontent.com/1775934/51929166-d80aee00-23f7-11e9-9a09-600feac104df.png)

**Comment by mquandalle** [comment]
J'ai l'impression que le problème a été corrigé.
