### ISSUE TITLE
Retours tests utilisateur du 19 février à Station F

### ISSUE THREAD

**Issue by laem** [betagouv/syso#471]
- une auto-entreprise d'avant 2019 dans la simulation actuelle va penser qu'elle a droit à l'ACRE.

On peut mettre :bulb:  un avertissement "pour une entreprise créée en 2019" sur les simulateurs. Pour les autres, on peut reposer sur la recherche d'entreprise, mais on a un problème pour ceux qui ont demandé à ne pas être dans la base publique. Deux solutions : est-ce qu'on peut avoir accès à l'API entreprise pour voir *toutes* les entreprises, et ne retourner que la date de création, qui alors désactiverait l'ACRE ?

- Après avoir renseigné le nom de l'entreprise, le clic sur le bouton "OK et simuler" ne marchait pas pour une auto-entreprise

- Pour une auto-entreprise, ne pas parler de "dirigeant" dans le bouton "simuler la rémunération du dirigeant" : risque de ne pas se reconnaître dans le terme dirigeant et ne pas cliquer.

- Remplacer le titre de année d'activité par "ACRE" ?

- retour unanime : le menu de navigation n'est pas reconnu en haut. Je pense que le principal problème c'est que le menu de la page d'accueil n'est pas reconnu par la suite. :bulb: Remplacer le menu du haut par "ma situation" et un bouton "Menu" très explicite qui permet de revenir sur l'accueil pour choisir une autre section, + renforcer les boutons précédent / suivant en bas de page ?
    - :+1: J'ai eu le même 

- un retour que je partage : on a trop de texte, trop de boutons sur les pages simulateur. Trop d'informations pour toutes les comprendre. 
    - :warning: J'ai eu le retour inverse : pas assez de détails, trop d'espace blanc inutilisé, polices trop grosse [sur bureau]. Il faut qu'on en discute

- Soit enlever les liens vers les pages /doc sur les simulateurs, mais à mon avis c'est une mauvaise idée pour des questions de SEO, soit améliorer les pages /doc pour bien faire comprendre que l'on est dans le détail. Par exemple avec un style visuel complètement différent, ou un bandeau bien visible "documentation". A voir dans les questions de graphisme ?
    - :question: Je ne compends pas le besoin. Qu'est-ce qui n'a pas fonctionné exactement ?

- mettre un avertissement sur les pages simuation et checklist d'embauche quand l'entreprise de la situation est une auto-entreprise : il est déconseillé d'embaucher dans ces situations, expliquer pourquoi.
    - Je pense qu'il faudrait carrément enlever ces parties pour l'auto-entreprise. Quitte à avoir un bouton "je veux embaucher" pour les micro, qui affiche une page spécifique explicant pourquoi ce n'est pas une bonne idée (même si c'est possible) et comment changer de régime.

- j'ai eu la question : "et ce statut juridique, je peux le changer facilement ?". Passer de EI à SAS pour s'associer ?

- le bouton "comparer ces régimes" était vu comme étrange, car du même style que les boutons <- et -> en bas mais aligné à gauche, ça semble étrange, pas envie de cliquer.

- il serait bon d'aligner les boutons des questions à choix multiples, par exemple l'année d'activité, pour que les changement dans les résultats de simulation au clic soient visibles sur l'écran d'un téléphone.

- sur les pages de création d'entreprise, gros intérêt à voir plus de détails sur la création en pratique : ça peut se faire dans le privé (400€) ou dans le public (200€), ça prend x semaines environ.

- quand on a rempli des données, par exemple le statut SAS, ou encore renseigné son entreprise, il faut faire comprendre qu'on a intégré ça. Par exemple avec un bouton "ma situation" toujours au même endroit sur toutes les pages, et aussi en introduction des simulateurs : nous vous affichons ce simulateur pour les assimilés car votre entreprise est une SAS. 
    - Je pense que ça fait doublon avec la situation

- Le bouton mensuel / annuel doit être situé avant le simulateur
- Le texte d'explication doit être situé avant le simulateur 
- Le simulateur AS doit integrer le brut / net avant impôts
- Dans le cas d'une entreprise à plusieurs salarié, on ne devrait pas parler de 'CA' 
- On ne voit pas qu'on peut affiner une simulation via les quicklink.    
- Ajouter un lien vers simuler un salarié depuis la simulation dirigeant
- La question avantage en nature ne devrait pas poper en premier, ou alors être moins ambigüe 
- Les suggestions ne sont pas très visible sur mobile 
- Le bouton précédent doit revenir à la question d'avant
- Il y a des liens qui ne remontent pas en haut de la page
- L'érgonomie n'est pas adapté au bureau (densité d'information trop faible, espace peut utilisé)
- L'infobulle des questions ne devrait pas apparaitre au dessus de la question
- La simulation n'est pas sauvegardée lorsqu'on revient sur la page (localstorage desactivé)
- Le CTA affiner la simulation est invisible en dessous des résultat 
- On ne sait pas qu'il y a quelque chose en dessous de la distributions des cotisations. Il faudrait avoir déjà les deux onglets, comme lorsque l'on commence à répondre aux questions
- Le texte "plus de questions !" n'est pas très positifs
- Fusionner le contenu informatif de la branche "chomage" et l'explication du calcul de la cotisations. Ou avoir un lien plus clair
- Le surlignage en jaune n'est pas compris tout de suite. Trouver d'autres moyens pour spécifier la règle qui s'applique à la situation    
- L'affordance de la checklist est très faible. 2 zones cliquable qui aboutissent à des actions différentes, mais pas différenciées visuellement.
- Lorsqu'on suit le lien pour connaître sa caisse de retraite, on a besoin de son IDCC. Il faudrait le préciser avant.
- Le lien du Tese manque d'informations contextuel "on m'a largué là"
- Expliciter ce que veut dire "DSN"
- Le liens vers la page service-public contrat de travail apporte peu de valeur, et perd l'utilisateur

- Le bouton "Signaler une erreur" est restreint et negatif. Trouver une formation plus englobante et positive.
- Mettre en avant le côté ouvert, contributif et le respect de la vie privée avec une phrase dans le footer.
### Feature request
- La taxe sur les salaires pour le secteur bancaire
- La possibilité de partager une simulation "sur slack"
- La possibiltié de voir d'un seul coup les variables de la simulation et de les modifer pour voir leur effet (vue 'expert') 
- Voir où l'on en est sur la situation qu'on a rempli. "Ma situation"

# Points positifs : 
- les utilisateur ont aimé la page de comparaison des régimes juridiques, c'est un travail inédit.
- un utilisateur a adoré la checklist de création
- l'explication "où vont vos cotiz" sur le simulateur embauche est super apprécié, et demandé pour les simulateurs des indépendants.
    - :+1: j'ai eu le même retour

# Retours divers : 
- j'ai eu 2 fois le retour sur la autoentrepreneur.urssaf.fr. Je pense que les problèmes découlent du fait que le site cumule nouvelle interface et anciennes briques.
  - le formulaire de création est très compliqué, pas traduit ni traductible automatiquement par Google
  - lors du parcours sur le site, on peut cliquer sur un lien et être déconnecté de son compte.

**Comment by laem** [comment]
@johangirod n'hésite pas à consolider cette liste directement avec tes remarques, je pense que beaucoup de points se recoupent.

**Comment by johangirod** [comment]
J'ai complété, mais je pense qu'il serait plus opportun de créer des issue pour chacun des points. Je vais m'en charger pour les plus urgents.

**Comment by johangirod** [comment]
J'ai fait une page wiki, plus adapté qu'une issue à rallonge. A partir de là, on pourra créer les issue au fur et à mesure

https://github.com/betagouv/syso/wiki/Retours-utilisateurs-tests-Station-F-du-19-02-2019
