### ISSUE TITLE
idée : fonction de partage après calcul

### ISSUE THREAD

**Issue by tbenett** [betagouv/syso#479]
J'aimerai bien pouvoir partager à des personnes le résultat calculé par le simulateur au lieu de leur demander de se rendre sur la page et de remplir un champ en particulier avec une certaine valeur.

Le partage pourraît avoir la forme d'un lien regénéré à chaque nouveau calcul ou bien généré à la demande.
Ou alors une  copie au format texte des résultats calculés.

----

I would like to share to others the calculated result instead of asking them to fill a field a specific value.

The sharing feature could be a link that would be generated at each new calculations or it could be generated at the demand of the user.

Or, it would be a text formatted copy of the results

**Comment by laem** [comment]
Merci beaucoup pour ta suggestion précise. Je ferme l'issue, car nous avions déjà évoqué le problème ici : #212, il est maintenant enrichi.
