### ISSUE TITLE
Le montant est modifié lorsque l'on clique sur un autre objectif de simulation

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#486]
1. je rentre un salaire brut (les montants sont calcules pour les autres cases)
2. je clique sur une des autres cases, total chargé
3. puis de nouveau sur salaire brut
bug -> le montant est modifié

**Comment by laem** [comment]
Le montant est recalculé avec l'approximation de l'inversion.

**Comment by laem** [comment]
On pourrait certes empêcher ce recalcul tant que l'utilisateur n'a rien saisi

**Comment by johangirod** [comment]
Cela venait du fait que l'on prenait `Math.floor` au lieu de `Math.round` lors de la selection du champs.

Fixed by 3bf0d0bf5862277303089454bd9ce955bbf2c057
