### ISSUE TITLE
Avoir des indicateurs objectifs pour comparer les régimes entre eux

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#511]
Notre comparateur de régime n'est pas satisfaisant.
![Screenshot_2019-04-09 Mon-entreprise fr Le guide officiel du créateur d'entreprise](https://user-images.githubusercontent.com/1775934/55802907-8195ec00-5ad9-11e9-86c3-719267f70505.png)

### Problèmes ergonomiques
- [ ] Les lignes doivent porter sur le même objet (IJSS, maladie, comptabilité) afin de faciliter la lecture horizontal de la comparaisons (un mode grille)
- [ ] La question pour le calcul du CA devrait aparaitre en dessous de la comparaison, pas au dessus (avec un texte : comparer les cotisations)

### Problèmes philosophiques
Aujourd'hui, en l'état actuel de nos connaissance, nous sommes incapable de fournir un comparatif justifié des différents régimes de protection sociale. Notament en ce qui concerne la justification de la différence des cotisations. 
- La retraite : est-ce que je cotise plus pour ma retraite avec le régime général ? Quels sont les différences pour calculer le montant de ma pension ? Que se passe-t'il si je suis salarié et que je deviens indépendant ? Est-ce que l'ACRE influe sur ce calcul ? Qu'en est-il de la prévoyance ? 
- Les cotisations IJSS et AT/MP : est-ce que le montant diffère ? Les règles de carence ? 

Cela demande un gros travail de recherche et de mise en forme. Pour les ressources, on peut s'appuyer sur les rapports du HCFIPS : 
- http://www.securite-sociale.fr/Rapport-sur-la-protection-sociale-des-non-salaries-et-son-financement
- http://www.securite-sociale.fr/IMG/pdf/rapport_hcfips_2016_chapitre_5.pdf
- http://www.securite-sociale.fr/IMG/pdf/hcfips_rapport_sur_la_protection_sociale_des_non_salaries_et_son_financement_tome_3_complements_statistiques.pdf

**Comment by johangirod** [comment]
J'ai commencé une [ébauche de comparaison de régime](https://docs.google.com/spreadsheets/d/1Alk6NYrSJrYuUnlHJfbrpzm--6By9WRLwzDAfJpOSLQ/edit?usp=sharing)

Quelques enseignements : 
- Le montant des IJSS sont les mêmes pour les auto-entrepreneurs et les indép (si l'on se base sur le revenu après abattement). Avec le même plafond. Il est donc conseillé de souscrire à une prévoyance complémentaire. L'accre ne semble pas changer ce montant.
- Pour l'auto-entrepreneur, le montant des pensions correspond à 50% de la moyenne des revenus après abattement pour les 3 dernières années, avec un plafond (le même que les IJSS), qui place à max 50€ / jour ([voir ici](https://www.legalstart.fr/fiches-pratiques/autoentrepreneur/retraite-autoentrepreneur/#ancre1). Il n'y a pas de retraite complémentaire, il est donc conseillé d'en souscrire une.

### Cas des polypensionnés
Il est précisé [ici](https://www.service-public.fr/particuliers/vosdroits/F31666) que les pensions des différentes caisses sont additionnées.

Pour le régime général, ce montant est [proratisé en fonction de la part de ma carrière effectué au régime général](https://www.service-public.fr/particuliers/vosdroits/F21552). Si je suis 50% régime général, j'ai 50% de ma retraite.

J'ose imaginer que c'est le même mécanisme qui prévaut pour les indépendants, mais il faut que je confirme cela (TODO).

On aurait donc : 
    - moyenne des 25 meilleures années (ou moins si le nombre d'année au R.G. est inferieur)
    - moyenne des 3 dernières années pour les micro-entrepreneurs

### A faire
- Retraite indépendant + retraite complémentaire
- Retraite proratisé pour les différentes caisses
- Retraite AGIRCC / ARCO (mode de fonctionnement différent)
- Que se passe-t'il si je suis auto-entrepreneur, puis salarié et que je ne ferme pas mon auto-entrerise (3 dernières années, le CA est 0)

**Comment by johangirod** [comment]
Ok je viens de me rendre compte que j'ai décris l'ancien mode de calcul (addition des différentes pensions au prorata de la durée d'en chaque régime).

A partir du 1er juillet 2017, cela a changé, il s'agit du système LURA : 
https://www.la-retraite-en-clair.fr/cid3190857/quelle-retraite-pour-les-cotisants-plusieurs-regimes-les-polypensionnes.html

On prends la moyenne des 25 * nombre année[régime] / nombre année total pour chaque régime.

```Par exemple, pour une personne qui a validé 120 trimestres auprès du régime général et 60 trimestres auprès du RSI, le calcul de son salaire moyen s’effectue de la manière suivante :

-dans le régime général : 25 x 120 trimestres/180 trimestres = 16,66, arrondi à 17 années ;
-dans le régime social des indépendants : 25 x 60 trimestres/180 trimestres = 8,33, arrondi à 8 années.
```

Dans le cas d'un cumul rsi + general sur la même période, ce nouveau système est désavantageux : 

```
Sur la sélection des 25 années pour calculer votre revenu annuel moyen : l'ancien mode de calcul est potentiellement désavantageux. En effet, il sélectionne obligatoirement un certain nombre d'années de référence parmi chacun des régimes auxquels vous avez cotisé, dans des proportions égales. Le résultat ne donne pas forcément vos 25 meilleures années tous revenus compris.


Exemple : si vous avez cotisé vos 10 ans (40 trimestres) comme indépendant avec des revenus très faibles, puis vos 35 ans (140 trimestres) au régime général avec de bien meilleurs revenus, vous serez contraint de faire entrer dans le calcul la moyenne de 6 années de mauvais revenus d'indépendant, et celle de seulement 19 années de bons revenus salariaux. C'est un scénario probable, par exemple si votre activité d'indépendant ne vous apportait que des revenus d'appoint.


Dans le nouveau mode de calcul, celui de la Lura, votre salaire annuel moyen sera calculé en tenant compte de tous vos revenus et en sélectionnant systématiquement les 25 meilleures années.
Sur le calcul de la pension à partir du salaire annuel moyen : l'ancien mode de calcul est potentiellement plus avantageux. En effet, il peut permettre de prendre en compte davantage de trimestres que la durée d'assurance requise, et plus de 4 trimestres par an pour le calcul de la pension.


On le voit dans notre exemple ci-dessus, dans lequel vous percevrez deux pensions :
Salaire annuel moyen x 50% x 140/165 pour la pension du régime général ;Revenu annuel moyen x 50% x 40/165 pour la pension du RSI.


Au total, vos revenus/salaires annuels moyens sont multipliés par 180/165, et donc augmentés.


Dans le nouveau système, c'est impossible : le maximum de pension est : revenu annuel moyen x 50% (sauf surcote).
```

**Comment by mquandalle** [comment]
Résolu par #530
