### ISSUE TITLE
L'absence du sessionStorage ne devrait pas faire planter le site

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#515]
D'après cet issue : https://betahelp.freshdesk.com/a/tickets/86
Visiblement, cela serait du à un paramètre modifié dans le navigateur. Quand bien même, on devrait s'assurer que le sessionStorage est là et est autorisé avant d'y faire appel.

Ceci dit, je ne trouve pas la trace de cette erreur dans sentry, il est probable que cela ne concerne qu'un nombre minime d'utilisateurs. A voir donc,

**Comment by revolunet** [comment]
hello ! on a ce souci lorsqu'on utilise un chromium "sécurisé" (piste ministère)

Voici une trace récupérée lorsque le widget est intégré dans le site "code du travail numérique"

![sim_embauche_console](https://user-images.githubusercontent.com/124937/57537181-0593fb80-7346-11e9-8668-6501d7a79db7.PNG)

**Comment by johangirod** [comment]
@revolunet merci pour la trace, j'ai pu corriger le problème facilement :+1: 
Tu me confirme que c'est bon pour toi (le fix est en prod) ?
