### ISSUE TITLE
Lâcher Internet Explorer

### ISSUE THREAD

**Issue by laem** [betagouv/syso#526]
Un employé de Microsoft a récemment appelé IE non pas un navigateur, mais un outil de compatibilité. 

3.2% de nos utilisateurs sont sur IE, et on leur consacre donc une partie bien plus importante de notre temps de développement. On peut parier qu'une bonne partie d'entre eux ont déjà le choix avec d'autres navigateurs installés sur leur machine.

On peut donc partir sur un bandeau "attention, votre navigateur est dépassé. Vous avez le choix entre utiliser un autre navigateur ou avoir une expérience dégradée du site".

**Comment by laem** [comment]
Autre solution, faire un mini-sondage : "Je ne peux pas installer un autre navigateur".

Autre idée : "sachez que le site est complètement utilisable sur votre mobile".

**Comment by johangirod** [comment]
Je propose un gros avertissement, avec la possibilité de continuer à utiliser le site avec le navigateur obsolete si l'utilisateur le souhaite. Mieux vaut lever toute ambiguité pour éviter de frustrer la personne qui utilise le site.
