### ISSUE TITLE
Problèmes de saisies numériques

### ISSUE THREAD

**Issue by laem** [betagouv/syso#541]
:bug: moins critiques 
- [x] Sur toute plateforme, une fois qu'on a saisi un chiffre, la saisie saute à la fin de l'input après le temps de debounce, dans la conversation
- [x] à investiguer : le double clic sur les boutons dans la conversation semble être nécessaire sur iOS

**Comment by laem** [comment]
Je confirme que 2) est a priori un problème de Browserstack : un click peut parfois provoquer un hover sur iPhone / iPad. On le voit bien quand on clique sur le bouton passer, ça déclenche un hover. Je teste en vrai lundi

**Comment by laem** [comment]
Eh bien non, c'était un problème iOS... #544

**Comment by laem** [comment]
Pour le problème de l'input et son saut de curseur, il suffit de réutiliser le composant CurrencyInput, génériciser son unité, et l'intégrer dans Input.js. Ces deux composants font plus ou moins la même chose ! 

https://github.com/betagouv/syso/pull/542/files

**Comment by johangirod** [comment]
A priori résolu dans #540
