### ISSUE TITLE
Alignement du symbole € sur la version anglaise

### ISSUE THREAD

**Issue by mquandalle** [betagouv/syso#558]
Le symbole € est mal aligné sur les champs de saisie qui n'ont pas le focus:

![alignement](https://user-images.githubusercontent.com/1730702/58804234-a8702a80-8611-11e9-8fc4-b8d4bede1d6f.png)

(j'ai vérifié ce n'est pas une régression de #551)

**Comment by johangirod** [comment]
Non, effectivement, c'est une regression qui a été introduite par #540. Auparavant, on positionnait le symbole euro du champs selectionné dynamiquement en adaptant la largeur de l'input en fonction du nombre de caractères. Mais cela posait un problème lors du rafraichissement du composant (le curseur revenait en début de saisi). 

On a donc le choix :
- Soit rétablir ce comportement (qui permet de garder l'uniformité visuelle entre champs / résultat)
- Soit changer de place le signe euro sur les champs non sélectionnés
