### ISSUE TITLE
Tests CI non executés sur les PR des contributeurs externes

### ISSUE THREAD

**Issue by mquandalle** [betagouv/syso#560]
Les tests de CircleCI ne sont pas exécutés si la personne qui ouvre la PR n'est pas membre du repo, exemple : #551 

![ci](https://user-images.githubusercontent.com/1730702/58867237-5d5e2200-86ba-11e9-9d26-ccc37e988bb8.png)

**Comment by mquandalle** [comment]
Il semble que CircleCI est exécuté uniquement sur les branches du repo (au moment du push de la branche), et non sur les PR. Peut-être que ça se configure quelque part ?

**Comment by rap2hpoutre** [comment]
Bonjour @mquandalle. Il semble que ce soit possible (cette saisie d'écran a été faite sur le produit POP)

<img width="1305" alt="Capture d’écran 2019-06-12 à 14 03 03" src="https://user-images.githubusercontent.com/1575946/59349968-3ab3b500-8d1b-11e9-8d32-b09321d337a2.png">

Donc sur un projet CircleCI : `settings` > `build settings` > `advanced settings` > `Build forked pull requests` > `on`

⚠️ Non testé : on n'en a pas besoin chez POP.

**Comment by mquandalle** [comment]
@laem @johangirod je n'ai pas accès à ce paramétrage, vous pouvez regarder ?

**Comment by johangirod** [comment]
@mquandalle bizarre que tu ne puisses pas y accéder si tu es dans l'orga github... 
J'ai changé le paramètre, ça devrait marcher maintenant :ok_hand: 
Merci pour le conseil @rap2hpoutre
