### ISSUE TITLE
Uniformiser les champs entre les différents simulateurs

### ISSUE THREAD

**Issue by johangirod** [betagouv/syso#561]
Aujourd'hui, on a quelques problèmes d'uniformisation entre les simulateurs : 
- Le net après impôt porte plusieurs nom (`revenu net` / `revenu net après impôts`)
- Le net de cotisations avant impots n'est pas présent partout et porte plusieurs nom (`revenu professionnel` / `revenu net`)
- Dans le cas des indépendant, la CSG n'est pas déduite totalement pour afficher le revenu professionnel. C'est donc l'équivalent du revenu net imposable qui est affiché à l'utilisateur, ce qui est moins intuitif que le revenu net avant impôts.

**Comment by mquandalle** [comment]
Résolu !
