### ISSUE TITLE
(ré)intégrer le lien vers le simulateur apprentissage

### ISSUE THREAD

**Issue by laem** [betagouv/syso#578]
https://www.alternance.emploi.gouv.fr/portail_alternance/jcms/gc_5504/simulateur-employeur

Il correspond bien au besoin des employeurs d'après @ppezziardi , et ça permettrait d'enrichir la page /sécurité-sociale avec un lien juste en-dessous du salarié : "simuler le salaire et les aides d'un alternant"

**Comment by johangirod** [comment]
Duplicate of #483
