### ISSUE TITLE
Simulateur en 2019 ou simulateur en fonction des années ?

### ISSUE THREAD

**Issue by laem** [betagouv/syso#609]
Une entreprise créée en 2019 arrive sur la question suivante :
![Screenshot_20190718-092758_Kiwi Browser](https://user-images.githubusercontent.com/1177762/61437888-6b03fa00-a93e-11e9-8de3-3c5610bf378d.jpg)

Si elle veut calculer `en avance` l'acre pour sa deuxième année, ce n'est l'usage que l'on avait défini.

Déjà

- [ ] préciser que ce sont des simulations EN 2019

**Comment by johangirod** [comment]
Effectivement, on fait des raccourcis douteuses pour les règles de rattachement CIPAV ou non. Pour être plus exact il faudrait demander : 
- l'année de création (avant 2018, 2018, 2019) => règles de rattachement et de question ACCRE
- et ensuite l'année d'activité => ACRE
