### ISSUE TITLE
Question CDD, puis question Temps partiel, puis question motif CDD

### ISSUE THREAD

**Issue by laem** [betagouv/syso#614]
On dirait que l'ordonnancement des questions selon le namespace dans nextStepSelector ne marche pas complètement.

**Comment by laem** [comment]
Lié à #610 .

**Comment by laem** [comment]
Mmh j'ai l'impression que ça dépend du navigateur. Un problème de tri implicite de structures de données fait différemment en fonction du nav ? J'ai ce problème seulement sur Kiwi sur Android. 
@mquandalle @johangirod quel est votre enchaïnement de question au début de la conversation ?

**Comment by johangirod** [comment]
@laem, sur firefox, j'ai bien : Temps Partiel [Non] -> CDD [oui] -> Motif CDD
