### ISSUE TITLE
Suppression de Redux-form

### ISSUE THREAD

**Issue by mquandalle** [betagouv/syso#632]
Je suis en train de supprimer Redux-form. Les avantages :

- Suppression de deux dépendances `redux-form` et `redux-batched-actions`
- Suppression d'actions inutiles dans l'historique redux
- Simplification du `state`, en particulier il y a actuellement deux représentations de l'état de la simulation l'une sous forme d'objets imbriqués qui vient de `redux-form`
(`{ 'contrat salarié' : { salaire: {net: 1400}}`) et l'autre sous forme de notation pointée que l'on utilise dans le code (`{'contrat salarié . salaire . net': 1400}`)
- Simplification de `TargetSelection`, au niveau du HTML toujours laisser affiché un `<input />` plutôt que de changer entre un `<span />` et `<input />` en fonction du contexte et se contenter de modifier le style CSS
- Résolution de #553 et #558

**Comment by laem** [comment]
Tu partirais donc sur un code natif, sans utiliser d'autres librairies ?
