### ISSUE TITLE
Conversion des valeurs entre le formulaire et le moteur

### ISSUE THREAD

**Issue by Morendil** [betagouv/syso#65]
La saisie de valeurs laisse à désirer, notamment la validation `number` dans `validators.js` autorise la saisie de nombres décimaux avec des virgules, mais saisir par exemple 2300,5 pour le salaire brut génère des NaN dans la barre de résultats et des "Infinity" dans certaines formules.

Par ailleurs il faudrait convertir entre la représentation des valeurs pour la saisie et une représentation interne: ainsi pour `taxe-apprentissage` la saisie du ratio d'alternants se fait sous la forme d'un pourcentage, mais on ne sait pas convertir 1 en 0,01: quand on saisit 1 dans ce champ c'est interprété comme 100%.

**Comment by Morendil** [comment]
Oops, bug toujours présent en prod et générant des :|

Je prends demain

**Comment by johangirod** [comment]
Quid de l'issue ? Je ne crois pas qu'elle soit encore d'actualité ?
