### ISSUE TITLE
Implémenter le régime Alsace-Moselle (taxe d'apprentissage, etc.)

### ISSUE THREAD

**Issue by Morendil** [betagouv/syso#66]
Ces cas particuliers ne sont pas pris en compte par #50, vérifier également si d'autres cotisations sont concernées.

**Comment by laem** [comment]
Oui, il y a la cotisation maladie salarié : https://github.com/sgmap/cout-embauche/wiki/Alsace-Moselle

**Comment by laem** [comment]
Je pense qu'il faut implémenter une version partielle de ce régime en se basant sur la commune (donc le département) renseignée, sans poser les questions supplémentaires.
