### ISSUE TITLE
Ajouter un champ charges de fonctionnement sur le simulateur auto-entrepreneur ?

### ISSUE THREAD

**Issue by mquandalle** [betagouv/syso#673]
Actuellement il y a une note en haut de page qui précise que les charges de fonctionnement doivent être déduite du net après impôt. C'est une simple soustraction mais peut-être pourrions-nous, plutôt que d'afficher cette note, afficher un champ « charges de fonctionnement » comme sur le simulateur indépendant ?

![image](https://user-images.githubusercontent.com/1730702/64865938-c39ffc80-d63a-11e9-9a9a-1b292cff025c.png)

cc @johangirod

**Comment by johangirod** [comment]
Il y était bien au départ. On en avait rediscuté avec Agnès, et on en était venu à la conclusion qu'il pouvait aboutir à une confusion. 

Je pense qu'il est assez intuitif pour quelqu'un qui commence en auto-entreprise qu'il y aura des dépenses liées à son activités. Le principe des charges de fonctionnement déductible est un concept supplémentaire dans la comptabilité, qui vient avec le dépassement de seuil.

Enfin, il est toujours plus interessant de limiter le nombre de champs dans un formulaire afin de réduire l'impact cognitif sur l'utilisateur.

**Comment by mquandalle** [comment]
Ok vous avez déjà réfléchi à la question et êtes arrivés à la solution actuelle, je ferme l'issue.
