### ISSUE TITLE
Indemnité compensatrices de congés payés

### ISSUE THREAD

**Issue by Morendil** [betagouv/syso#91]
Les congés payés c'est compliqué :)

Un dump de quelques références et simulateurs:
- https://www.service-public.fr/particuliers/vosdroits/F33927
- https://www.zen-avec-mon-assmat.com/indemnites-de-conges-payes/
- http://www.efl.fr/actualites/social/conges/details.html?ref=ui-6a8d7a5a-229d-4303-969f-a05a59b77971
- http://www.calculer.com/calcul-indemnites-compensatrices-de-conges-payes/calcul-indemnites-compensatrices-de-conges-payes.php
- https://www.l-expert-comptable.com/calculateurs/calcul-indemnites-compensatrices-de-conges-payes.html

**Comment by laem** [comment]
Complexité additionnelle : il faut probablement pouvoir jongler entre congés ouvrés et ouvrables (nombre légal : 25 ou 30), comme on doit pouvoir jongler entre salaire mensuel ou hebdomadaire ou...

**Comment by mquandalle** [comment]
Je ferme car c'est implémenté dans le moteur (au moins pour les CDD), on peut ré-ouvrir des issues plus spécifiques pour améliorer l'implémentation. https://mon-entreprise.fr/documentation/contrat-salarié/CDD/compensation-pour-congés-non-pris
